// Code generated by mockery v1.0.0. DO NOT EDIT.
package mockdriver

import mock "github.com/stretchr/testify/mock"

// CommitInfo is an autogenerated mock type for the CommitInfo type
type CommitInfo struct {
	mock.Mock
}

// ObjectURL provides a mock function with given fields:
func (_m *CommitInfo) ObjectURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
