// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import context "context"
import driver "github.com/NVIDIA/vdisc/pkg/storage/driver"
import mock "github.com/stretchr/testify/mock"

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, url
func (_m *Creator) Create(ctx context.Context, url string) (driver.ObjectWriter, error) {
	ret := _m.Called(ctx, url)

	var r0 driver.ObjectWriter
	if rf, ok := ret.Get(0).(func(context.Context, string) driver.ObjectWriter); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.ObjectWriter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
