// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import driver "github.com/NVIDIA/vdisc/pkg/storage/driver"
import mock "github.com/stretchr/testify/mock"

// ObjectWriter is an autogenerated mock type for the ObjectWriter type
type ObjectWriter struct {
	mock.Mock
}

// Abort provides a mock function with given fields:
func (_m *ObjectWriter) Abort() {
	_m.Called()
}

// Commit provides a mock function with given fields:
func (_m *ObjectWriter) Commit() (driver.CommitInfo, error) {
	ret := _m.Called()

	var r0 driver.CommitInfo
	if rf, ok := ret.Get(0).(func() driver.CommitInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.CommitInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: p
func (_m *ObjectWriter) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
