// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import context "context"

import mock "github.com/stretchr/testify/mock"
import os "os"

// Readdirer is an autogenerated mock type for the Readdirer type
type Readdirer struct {
	mock.Mock
}

// Readdir provides a mock function with given fields: ctx, url
func (_m *Readdirer) Readdir(ctx context.Context, url string) ([]os.FileInfo, error) {
	ret := _m.Called(ctx, url)

	var r0 []os.FileInfo
	if rf, ok := ret.Get(0).(func(context.Context, string) []os.FileInfo); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.FileInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
