// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import context "context"

import mock "github.com/stretchr/testify/mock"

// Remover is an autogenerated mock type for the Remover type
type Remover struct {
	mock.Mock
}

// Remove provides a mock function with given fields: ctx, url
func (_m *Remover) Remove(ctx context.Context, url string) error {
	ret := _m.Called(ctx, url)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
