// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import mock "github.com/stretchr/testify/mock"

// VisitorTraversal is an autogenerated mock type for the VisitorTraversal type
type VisitorTraversal struct {
	mock.Mock
}

// DepthFirst provides a mock function with given fields:
func (_m *VisitorTraversal) DepthFirst() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
