// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import mock "github.com/stretchr/testify/mock"
import os "os"

// Visitor is an autogenerated mock type for the Visitor type
type Visitor struct {
	mock.Mock
}

// VisitDir provides a mock function with given fields: baseURL, files
func (_m *Visitor) VisitDir(baseURL string, files []os.FileInfo) error {
	ret := _m.Called(baseURL, files)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []os.FileInfo) error); ok {
		r0 = rf(baseURL, files)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
