// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import mock "github.com/stretchr/testify/mock"

// VisitorPredicate is an autogenerated mock type for the VisitorPredicate type
type VisitorPredicate struct {
	mock.Mock
}

// ShouldVisitDir provides a mock function with given fields: url
func (_m *VisitorPredicate) ShouldVisitDir(url string) (bool, error) {
	ret := _m.Called(url)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
