// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockdriver

import mock "github.com/stretchr/testify/mock"

// VisitorConcurrency is an autogenerated mock type for the VisitorConcurrency type
type VisitorConcurrency struct {
	mock.Mock
}

// Concurrency provides a mock function with given fields:
func (_m *VisitorConcurrency) Concurrency() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
